# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(related_name='choices', to='polls.Question'),
        ),
    ]
